module.exports = async function(db) {
  await db.Customer_Card.bulkCreate([
    {
      card_number: 'card_number_1',
      cust_surname: 'Kolesnyk',
      cust_name: 'Max',
      cust_patronymic: 'Artemovich',
      phone_number: '+380958091390',
      city: 'Kyiv',
      street: 'Myshugi 3',
      zip_code: '2140',
      percent: 10,
    },
    {
      card_number: 'card_number_2',
      cust_surname: 'Gorulya',
      cust_name: 'Katya',
      cust_patronymic: 'Igorivna',
      phone_number: '+380990139635',
      city: 'Kyiv',
      street: 'Radunska 2',
      zip_code: '2140',
      percent: 25,
    },
    {
      card_number: 'card_number_3',
      cust_surname: 'Zila',
      cust_name: 'Dima',
      cust_patronymic: 'Mihailovich',
      phone_number: '+380956782331',
      city: 'Mikolaiv',
      street: 'Stalina 3',
      zip_code: '4212',
      percent: 30,
    },
    {
      card_number: 'card_number_4',
      cust_surname: 'Sorokopud',
      cust_name: 'Yulia',
      cust_patronymic: 'Mihailivna',
      phone_number: '+380956788931',
      city: 'Kyiv',
      street: 'Shastlive 37',
      zip_code: '56902',
      percent: 70,
    },
    {
      card_number: 'card_number_5',
      cust_surname: 'Tryhub',
      cust_name: 'Yulia',
      cust_patronymic: 'Volodimirivna',
      phone_number: '+380676782331',
      city: 'Kyiv',
      street: 'Radynskya 23',
      zip_code: '2312',
      percent: 30,
    },
    {
      card_number: 'card_number_6',
      cust_surname: 'Hristenko',
      cust_name: 'Olena',
      cust_patronymic: 'Ivanivna',
      phone_number: '+380983482331',
      city: 'Lviv',
      street: 'Lenina 43',
      zip_code: '90876',
      percent: 25,
    },
    {
      card_number: 'card_number_7',
      cust_surname: 'Holovach',
      cust_name: 'Inna',
      cust_patronymic: 'Ivanivna',
      phone_number: '+380982312331',
      city: 'Lviv',
      street: 'Oleni 89',
      zip_code: '987234',
      percent: 30,
    },
  ]);
};
