module.exports = async function(db) {
  await db.Employee.bulkCreate([
    {
      id_employee: 'id_empl_1' ,
      email: 'polina@gmail.com',
      password: 'polina',
      empl_surname: 'Podopryhora',
      empl_name: 'Polina',
      empl_patronymic: 'Romanivna' ,
      role: 'seller',
      salary: 7000 ,
      date_of_birth: '2000-08-26' ,
      date_of_start:  '2021-01-17',
      phone_number: '+380679876534',
      city: 'Kyiv' ,
      street: 'Kashtanova 8' ,
      zip_code: '02345'
    },
    {
      id_employee: 'id_empl_2',
      email: 'malyar@gmail.com',
      password: 'nastya',
      empl_surname: 'Malyar',
      empl_name: 'Nastya',
      empl_patronymic: 'Vitaliivna' ,
      role: 'manager',
      salary: 13000 ,
      date_of_birth: '2001-01-19' ,
      date_of_start:  '2020-09-21',
      phone_number: '+380678076543',
      city: 'Kyiv' ,
      street: 'Liskivskya 12' ,
      zip_code: '02222'
    },
    {
      id_employee: 'id_empl_3' ,
      email: 'dima@gmail.com',
      password: '3',
      empl_surname: 'Babenich',
      empl_name: 'Dima',
      empl_patronymic: 'Viktorovich' ,
      role: 'seller',
      salary: 12000 ,
      date_of_birth: '2001-01-17' ,
      date_of_start:  '2020-09-20',
      phone_number: '+380674476543',
      city: 'Mikolaiv' ,
      street: 'Kolena 65' ,
      zip_code: '34252'
    },
    {
      id_employee: 'id_empl_4' ,
      email: '4',
      password: '4',
      empl_surname: 'Petryk',
      empl_name: 'Ivan',
      empl_patronymic: 'Ivanovich' ,
      role: 'seller',
      salary: 13000 ,
      date_of_birth: '1999-12-17' ,
      date_of_start:  '2020-09-22',
      phone_number: '+380679976544',
      city: 'Kyiv' ,
      street: 'Khreshatyk 14' ,
      zip_code: '78754'
    },
    {
      id_employee: 'id_empl_5' ,
      email: '5',
      password: '5',
      empl_surname: 'Vasylyk',
      empl_name: 'Anna',
      empl_patronymic: 'Yaroslavivna' ,
      role: 'manager',
      salary: 26000 ,
      date_of_birth: '1973-12-17' ,
      date_of_start:  '2018-09-22',
      phone_number: '+380557876544',
      city: 'Kyiv' ,
      street: 'Mishygi 14' ,
      zip_code: '38754'
    },
  ]);
};
